version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:6.8.12
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "cluster.name=personium"
      - "network.host=0.0.0.0"
      - "action.auto_create_index=.watches,.triggered_watches,.watcher-history-*"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "indices.fielddata.cache.size=80%"
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - 61616:61616
      - 8161:8161
  memcached-lock:
    image: memcached:1.6.7
    ports:
      - 11211:11211

  memcached-cache:
    image: memcached:1.6.7
    ports:
      - 11212:11211

  nginx:
    build:
      context: ./dockerfiles/nginx
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:172.101.0.1"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.101.0.0/16